global:
  resolve_timeout: 5m

route:
  receiver: 'team-email'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'team-email'
  email_configs:
    - to: 'butas.rafael@yahoo.com'
      from: 'alertmanager@example.com'
      smarthost: 'smtp.example.com:587'
      auth_username: 'alertmanager@example.com'
      auth_password: 'your-smtp-password'

# (Optional) Slack receiver example
# - name: 'slack-notifications'
#   slack_configs:
#     - api_url: 'https://hooks.slack.com/services/…'
#       channel: '#alerts'
