global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "recording_rules.yml"
  - "alert_rules.yml"


alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:

  - job_name: fastapi_app
    metrics_path: /metrics/raw
    static_configs:
      - targets: ['web:8000']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node_exporter
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'gpu'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['dcgm-exporter:9400']
