[server]
# where clients connect
bind_addr      = "0.0.0.0:2333"

# default token, so you don't have to repeat per-service
default_token  = "REPLACE_WITH_A_LONG_RANDOM_SECRET"

heartbeat_interval = 30      # optional tuning

[server.services.urban_ai_api]
# service name must match client.services.* below
token      = "REPLACE_WITH_A_LONG_RANDOM_SECRET"
# expose your API on port 5202
bind_addr  = "0.0.0.0:5202"
