"""initial

Revision ID: 31c58f570c1a
Revises: 
Create Date: 2025-08-30 11:53:59.181413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
import pgvector


# revision identifiers, used by Alembic.
revision: str = '31c58f570c1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension first
    op.execute(text("CREATE EXTENSION IF NOT EXISTS vector;"))
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'authority', 'admin', name='role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_username', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authority_username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('num_frames', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geohash6', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('process_ms_total', sa.Integer(), nullable=True),
    sa.Column('static_filename', sa.String(), nullable=True),
    sa.Column('thumbnail_filename', sa.String(), nullable=True),
    sa.Column('summary_description', sa.Text(), nullable=True),
    sa.Column('summary_solution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_geohash6'), 'media', ['geohash6'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frame_created_at'), 'frame', ['created_at'], unique=False)
    op.create_table('detection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('x1', sa.Float(), nullable=True),
    sa.Column('y1', sa.Float(), nullable=True),
    sa.Column('x2', sa.Float(), nullable=True),
    sa.Column('y2', sa.Float(), nullable=True),
    sa.Column('mask_rle', sa.JSON(), nullable=True),
    sa.Column('mask_polygon', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('track_thumbnail_url', sa.String(), nullable=True),
    sa.Column('frames_detected', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('yolo', 'gpt_dino', 'sam_fallback', name='detection_source_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'ignored', name='issue_status_enum'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.username'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.username'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_class_name'), 'detection', ['class_name'], unique=False)
    op.create_index('ix_detection_class_name_created_at', 'detection', ['class_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_detection_created_at'), 'detection', ['created_at'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity_enum'), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'ignored', name='issue_status_enum'), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_chunk_class_created', 'rag_chunks', ['class_name', 'created_at'], unique=False)
    op.create_index('ix_rag_chunk_severity_status', 'rag_chunks', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_rag_chunks_assigned_to'), 'rag_chunks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_rag_chunks_class_name'), 'rag_chunks', ['class_name'], unique=False)
    op.create_index(op.f('ix_rag_chunks_created_at'), 'rag_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_chunks_resolved_at'), 'rag_chunks', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_rag_chunks_severity'), 'rag_chunks', ['severity'], unique=False)
    op.create_index(op.f('ix_rag_chunks_status'), 'rag_chunks', ['status'], unique=False)
    op.create_index(op.f('ix_rag_chunks_uploaded_at'), 'rag_chunks', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_rag_chunks_verified_at'), 'rag_chunks', ['verified_at'], unique=False)
    op.create_index(op.f('ix_rag_chunks_verified_by'), 'rag_chunks', ['verified_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_chunks_verified_by'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_verified_at'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_uploaded_at'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_status'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_severity'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_resolved_at'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_created_at'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_class_name'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_assigned_to'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunk_severity_status', table_name='rag_chunks')
    op.drop_index('ix_rag_chunk_class_created', table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_detection_created_at'), table_name='detection')
    op.drop_index('ix_detection_class_name_created_at', table_name='detection')
    op.drop_index(op.f('ix_detection_class_name'), table_name='detection')
    op.drop_table('detection')
    op.drop_index(op.f('ix_frame_created_at'), table_name='frame')
    op.drop_table('frame')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_media_geohash6'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_table('media')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
    
    # Drop pgvector extension (optional - you might want to keep it)
    op.execute(text("DROP EXTENSION IF EXISTS vector;"))
