"""add_summary_fields_to_media

Revision ID: 4dec9b9b7b40
Revises: 96dfa77a6367
Create Date: 2025-08-24 21:31:42.637575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4dec9b9b7b40'
down_revision: Union[str, None] = '96dfa77a6367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('summary_description', sa.Text(), nullable=True))
    op.add_column('media', sa.Column('summary_solution', sa.Text(), nullable=True))
    # NOTE: Keeping the vector index - it's needed for RAG similarity search
    # op.drop_index(op.f('idx_rag_chunks_embedding_ivfflat'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Not recreating index since we didn't drop it
    # op.create_index(op.f('idx_rag_chunks_embedding_ivfflat'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('media', 'summary_solution')
    op.drop_column('media', 'summary_description')
    # ### end Alembic commands ###
