"""Add UUID filenames to media table

Revision ID: 5073ee33aeb7
Revises: 7cd4323810e7
Create Date: 2025-08-26 08:45:52.239528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '5073ee33aeb7'
down_revision: Union[str, None] = '7cd4323810e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('static_filename', sa.String(), nullable=True))
    op.add_column('media', sa.Column('thumbnail_filename', sa.String(), nullable=True))
    op.drop_index(op.f('idx_rag_chunks_embedding_ivfflat'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_rag_chunks_embedding_ivfflat'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('media', 'thumbnail_filename')
    op.drop_column('media', 'static_filename')
    # ### end Alembic commands ###
