"""add_title_to_chat_sessions

Revision ID: 96dfa77a6367
Revises: 660f4182f1af
Create Date: 2025-08-24 19:58:14.344269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '96dfa77a6367'
down_revision: Union[str, None] = '660f4182f1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('title', sa.String(length=200), nullable=True))
    # NOTE: Keeping the vector index - it's needed for RAG similarity search
    # op.drop_index(op.f('idx_rag_chunks_embedding_ivfflat'), table_name='rag_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Not recreating index since we didn't drop it
    # op.create_index(op.f('idx_rag_chunks_embedding_ivfflat'), 'rag_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('chat_sessions', 'title')
    # ### end Alembic commands ###
